version: '3'

services:
        dbos:
                image: mysql:5.7
                volumes:
                        - mysql_storage:/var/lib/mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: rootpass
                        MYSQL_USER: ajay
                        MYSQL_PASSWORD: ajay
                        MYSQL_DATABASE: mydb
        myadmin:
                image: phpmyadmin/phpmyadmin:latest
                restart: always
                depends_on:
                        - dbos
                ports:
                        - 8081:80
                environment:
                        PMA_PORT: 3306
                        PMA_ARBITRARY: 1
                        PMA_HOST: mysql

volumes:
        mysql_storage: 
